[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "abacustools"
version = "0.0.1"
description = "Tools for accompanying using ABACUS"
readme = "README.md"
authors = [
    { name = "ahxbcn", email = "zh20150625@163.com" },
]
license = "LGPL-3.0-or-later"
classifiers = [
    "Natural Language :: English",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3 :: Only",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Environment :: Console",
]
requires-python = ">=3.9"
dependencies = ["numpy", "rich", "pymatgen", "phonopy", "seekpath", "matplotlib", "ase"]

[project.scripts]
abacustools = "abacustools.main:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
abacustools = ["io/input-params.json", "core/default_config.yaml"]
